name: bag_wiki_admin
description: Admin dashboard for managing Bag Wiki content
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.8.1

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

# Configuration for flutter_launcher_icons
flutter_icons:
  image_path: "assets/images/logo.png"
  web:
    generate: true
  
  
  # olor: "#1A1A2E" # Match your dark theme background
#     theme_color: "#9353D3" # Match your primary theme color
#   web:
#     generate: true
#     image_path: "assets/images/logo.png"
#     background_color: "#1A1A2E" # Match your dark theme background
#     theme_color: "#9353D3" # Match your primary theme color
#   windows:
#     generate: true
#     image_path: "assets/images/logo.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true



  assets:
    - assets/
    - assets/images/
    - assets/images/logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
